"""Evolution 门面 — 组合子模块，对外提供统一接口。"""
from __future__ import annotations
import json
import logging
from pathlib import Path

from evocli_soul.evolution.pattern_detector import (
    Pattern, extract_sequences, detect_patterns, PATTERN_THRESHOLD
)
from evocli_soul.evolution.skill_draft      import SkillDraft, generate as generate_draft
from evocli_soul.evolution.failure_miner    import FailureMiner
from evocli_soul.evolution.knowledge_classifier import KnowledgeClassifier, Transferability
from evocli_soul.evolution import decay_detector
from evocli_soul.evolution import scheduler as _scheduler
from evocli_soul.evolution.circuit_breaker  import get_circuit_breaker

log = logging.getLogger("evocli.evolution")

__all__ = ["EvolutionEngine"]

# Skill 草案存放目录：直接使用 ~/.evocli/skills/（与 CLI evocli evolve drafts 路径一致）
# 草案文件写入时携带 status = "draft"，CLI 已过滤该字段展示待审查列表。
# 用户审查后手动修改 status 为 "trusted" 或执行 evocli skill run <id> 激活。
PROPOSALS_DIR = Path.home() / ".evocli" / "skills"


def _draft_to_toml(draft: dict) -> str:
    """将 Skill 草案字典转换为 TOML 格式字符串。

    生成 SkillEngine 可解析的 [skill] + [[skill.steps]] 格式，
    与 evocli/evocli-soul/evocli_soul/builtin_skills/ 中的格式完全一致。
    draft 状态文件由 SkillEngine 加载但不自动执行（需用户显式 evocli skill run <id>）。
    """
    steps_lines = []
    for i, step in enumerate(draft.get("steps", []), 1):
        action   = step.get("action", "unknown")
        needs_ok = "true" if step.get("requires_approval") else "false"
        steps_lines.append(
            f'\n[[skill.steps]]\nid = "step_{i}"\naction = "{action}"\n'
            f'params = {{}}\nrequires_approval = {needs_ok}'
        )

    keywords_json = json.dumps(draft.get("trigger_keywords", []), ensure_ascii=False)
    pattern_str   = " → ".join(draft.get("trigger_keywords", []))
    return (
        f'# Auto-generated Skill Draft\n'
        f'# Generated by Evolution Engine from repeated behavior pattern\n'
        f'# Review then run: evocli skill run {draft["id"]} --dry-run\n\n'
        f'[skill]\n'
        f'id = "{draft["id"]}"\n'
        f'name = "{draft.get("name", "Auto Skill")}"\n'
        f'description = "Auto-generated: detected pattern {pattern_str}"\n'
        f'version = "0.1.0"\n'
        f'status = "draft"\n\n'
        f'[skill.trigger]\n'
        f'keywords = {keywords_json}\n'
        + "".join(steps_lines) + "\n"
    )


def _persist_drafts(drafts: list[dict]) -> int:
    """将 Skill 草案保存到 PROPOSALS_DIR，返回新保存的数量（跳过已存在的）。"""
    PROPOSALS_DIR.mkdir(parents=True, exist_ok=True)
    saved = 0
    for draft in drafts:
        draft_id = draft.get("id", "unknown")
        path = PROPOSALS_DIR / f"{draft_id}.toml"
        if path.exists():
            continue  # 避免重复写入同一草案
        try:
            path.write_text(_draft_to_toml(draft), encoding="utf-8")
            log.info("Evolution: skill draft saved → %s", path)
            saved += 1
        except Exception as e:
            log.warning("Evolution: failed to save draft %s: %s", draft_id, e)
    return saved


class EvolutionEngine:
    """门面：协调所有 evolution 子模块（Section 9）。"""

    def __init__(self, bridge, skill_engine=None):
        self.bridge             = bridge
        self.skill_engine       = skill_engine
        self._failure_miner     = FailureMiner(bridge)
        self._knowledge_clf     = KnowledgeClassifier()

    async def observe(self, params: dict) -> dict:
        """主观察入口：模式检测 + 失败挖掘 + 草案持久化。"""
        events = params.get("events", [])

        result: dict = {"patterns": [], "drafts": [], "failures_mined": 0, "drafts_saved": 0}

        # Section 9.5：模式检测
        if len(events) >= PATTERN_THRESHOLD:
            sequences   = extract_sequences(events)
            patterns    = detect_patterns(sequences)
            significant = [p for p in patterns if p.frequency >= PATTERN_THRESHOLD]
            drafts      = [d for p in significant[:3] if (d := generate_draft(p))]
            result["patterns"] = [{"sequence": p.sequence, "frequency": p.frequency} for p in significant]
            result["drafts"]   = [{"id": d.id, "name": d.name, "trigger_keywords": d.trigger_keywords, "steps": d.steps} for d in drafts]

            # Fix: 将草案持久化到磁盘，而非只打 log
            # 用户可通过 evocli evolve drafts 查看，审查后 evocli skill import 激活
            if result["drafts"]:
                saved = _persist_drafts(result["drafts"])
                result["drafts_saved"] = saved
                if saved:
                    log.info("Evolution: %d new skill draft(s) saved to %s", saved, PROPOSALS_DIR)
                    # GAP-5 (active path): Notify TUI using soul_status which Rust TUI DOES handle.
                    # This is the active evolution entry point (main.py uses evocli_soul.evolution,
                    # not evolution_engine.py). The soul_status "ready" message is pushed as a
                    # System chat message in the TUI.
                    try:
                        from evocli_soul.rpc import emit_event
                        import asyncio as _asyncio
                        names = ", ".join(d.get("name", "?") for d in result["drafts"][:2])
                        if len(result["drafts"]) > 2:
                            names += f" (+{len(result['drafts'])-2} more)"
                        _asyncio.create_task(emit_event("soul_status", {
                            "status":  "ready",
                            "message": (
                                f"🔁 Evolution: {saved} new Skill pattern(s) — {names}. "
                                f"Run `evocli evolve drafts` to review."
                            ),
                        }))
                    except Exception as _ev_err:
                        log.debug("Evolution TUI notify failed (non-fatal): %s", _ev_err)

        # Section 9.6：失败知识挖掘
        if events:
            project = params.get("project_id", ".")
            mine_result = await self._failure_miner.mine(events, project)
            result["failures_mined"] = mine_result.get("mined", 0)

        log.info("Evolution scan: %d patterns, %d drafts (%d new), %d failures",
                 len(result["patterns"]), len(result["drafts"]),
                 result["drafts_saved"], result["failures_mined"])
        return result

    async def check_skill_decay(self, skill_id: str, project: str) -> dict:
        """Section 9.7：Skill 腐化检测。"""
        return await decay_detector.check(skill_id, project, self.bridge)

    async def promote_knowledge(self, memory_item: dict) -> dict:
        """Section 9.9：跨项目知识迁移——将 P1 知识提升到 P2/P3。"""
        return await self._knowledge_clf.promote_if_transferable(memory_item, self.bridge)

    def start_background_scheduler(self) -> None:
        """Section 9.5+9.6：启动进化飞轮后台调度（模式检测 + 记忆蒸馏）。

        Fix: 现在同时启动：
        - 每 10 分钟 Evolution scan（读 events.db → 模式检测 → 草案持久化）
        - 每 5 分钟 Memory distillation（读 events.db → 蒸馏经验 → 写 LanceDB）
        这样即使用户从不显式 session.pause，记忆也会随时间自动积累。
        """
        from evocli_soul.memory_distill import MemoryDistiller
        distiller = MemoryDistiller(self.bridge)
        _scheduler.start(observe_fn=self.observe, distill_fn=distiller.run)
